### ISSUE TITLE
Error on options dialog (Mac OS X)

### ISSUE THREAD

**Issue by froschdesign** [beberlei/netbeans-php-enhancements#7]
When i try to click on the “Code Sniffer“-Button in the options dialog, Netbeans shows the following error message:

```
java.lang.NoClassDefFoundError: javax/swing/GroupLayout
    at de.whitewashing.php.cs.CodeSnifferPanel.initComponents(CodeSnifferPanel.java:39)
    at de.whitewashing.php.cs.CodeSnifferPanel.<init>(CodeSnifferPanel.java:16)
    at de.whitewashing.php.cs.CodeSnifferOptionsPanelController.getPanel(CodeSnifferOptionsPanelController.java:60)
    at de.whitewashing.php.cs.CodeSnifferOptionsPanelController.getComponent(CodeSnifferOptionsPanelController.java:47)
    at org.netbeans.modules.options.advanced.Model$DelegatingController.getComponent(Model.java:310)
    at org.netbeans.modules.options.advanced.Model.getPanel(Model.java:150)
    at org.netbeans.modules.options.advanced.AdvancedPanel.handleTabSwitched(AdvancedPanel.java:197)
    at org.netbeans.modules.options.advanced.AdvancedPanel.access$100(AdvancedPanel.java:72)
    at org.netbeans.modules.options.advanced.AdvancedPanel$1.stateChanged(AdvancedPanel.java:80)
    at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:290)
    at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:222)
    at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:116)
    at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:50)
    at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:478)
    at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:464)
    at apple.laf.AquaTabbedPaneUI$MouseHandler.mouseReleased(AquaTabbedPaneUI.java:1661)
    at java.awt.Component.processMouseEvent(Component.java:5583)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3135)
    at java.awt.Component.processEvent(Component.java:5348)
    at java.awt.Container.processEvent(Container.java:2010)
    at java.awt.Component.dispatchEventImpl(Component.java:4050)
    at java.awt.Container.dispatchEventImpl(Container.java:2068)
    at java.awt.Component.dispatchEvent(Component.java:3885)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4256)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:3936)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:3866)
    at java.awt.Container.dispatchEventImpl(Container.java:2054)
    at java.awt.Window.dispatchEventImpl(Window.java:1791)
    at java.awt.Component.dispatchEvent(Component.java:3885)
[catch] at java.awt.EventQueue.dispatchEvent(EventQueue.java:463)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:104)
    at java.awt.EventDispatchThread.pumpOneEventForHierarchy(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:176)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:110)
```

**Comment by cyberaguiar** [comment]
What version of java and netbeans you are using?

**Comment by cyberaguiar** [comment]
Its look a java 1.5 issue (http://kendes.blogspot.com/2008/03/grouplayout-converting-java-6-to-java-5.html). Please try update and test again.

**Comment by dazweeja** [comment]
I had this problem too and solved it by making "Java SE 6" the default for Java Applications in:
/Applications/Utilities/Java/Java Preferences.App

**Comment by froschdesign** [comment]
You are right. It was the wrong java version.
Thanks!
